// 分类配置
window.categoryConfig = [
{ dh: "top", glm: "首页", qz: 0 },
  { dh: "1", glm: "开发", qz: 1 },
  { dh: "2", glm: "3D模型", qz: 2 },
  { dh: "3", glm: "游戏", qz: 3 },
  { dh: "4", glm: "实用工具", qz: 4 },
  { dh: "5", glm: "投稿", qz: 5 },
  { dh: "6", glm: "美术", qz: 6 },
  { dh: "7", glm: "宣传000", qz: 7 },

  { dh: "8", glm: "影视娱乐", qz: 9 },
  { dh: "9", glm: "开发工具", qz: 9 },
  { dh: "10", glm: "教育资源", qz: 9 },
  { dh: "11", glm: "云与空间", qz: 9 },
  { dh: "12", glm: "学术与论文", qz: 9 },
];

// 网站配置
window.siteConfig = [
	//首页
	{ wz: "https://www.bilibili.com/", wzm: "哔哩哔哩", gl: "top", qz: 1, bz: "" },
	  { wz: "https://www.douyin.com/", wzm: "抖音", gl: "top", qz: 2, bz: "" },
	  { wz: "https://mcdev.webapp.163.com/#/square", wzm: "网易开发后台", gl: "top", qz: 3, bz: "" },
	  { wz: "https://mc.163.com/dev/mcmanual/mc-dev/mcdocs/1-ModAPI/接口/通用/索引.html", wzm: "网易API", gl: "top", qz: 4, bz: "MC接口文档" },
	  { wz: "https://wiki.biligame.com/mc/Minecraft_Wiki", wzm: "MCWIKI", gl: "top", qz: 5, bz: "Minecraft中文Wiki" },
	  { wz: "https://cn.bing.com/translator", wzm: "Bing翻译", gl: "top", qz: 6, bz: "" },
	  { wz: "https://docs.qq.com/desktop", wzm: "腾讯文档", gl: "top", qz: 7, bz: "" },
	  { wz: "https://www.kdocs.cn/latest", wzm: "WPS文档", gl: "top", qz: 8, bz: "" },
	  { wz: "https://cloud.189.cn/web/main/file/folder/324011178383615123", wzm: "天翼云盘", gl: "top", qz: 9, bz: "" },
	  { wz: "https://wx.mail.qq.com/home/index", wzm: "QQ邮箱", gl: "top", qz: 10, bz: "" },
	  { wz: "https://github.com/", wzm: "GitHub", gl: "top", qz: 11, bz: "" },
	  { wz: "https://ringozia.github.io/tab/", wzm: "RingoTab", gl: "top", qz: 11, bz: "RingoTab" },
	  { wz: "https://www.kimi.com/zh/", wzm: "Kimi", gl: "top", qz: 12, bz: "" },
	  { wz: "https://www.doubao.com/chat/", wzm: "豆包", gl: "top", qz: 13, bz: "" },
	  { wz: "https://dayone.me/all", wzm: "Dayone", gl: "top", qz: 14, bz: "" },
	  { wz: "https://lmarena.ai/?mode=direct", wzm: "Lmarena", gl: "top", qz: 15, bz: "整合各种ai工具" },
	  { wz: "https://aistudio.google.com/prompts/new_chat?model=gemini-3-pro-preview", wzm: "AI Studio", gl: "top", qz: 16, bz: "Gemini Pro预览" },
	
	
	
	
	
  // 开发
  {
    wz: "https://mc.163.com/dev/mcmanual/mc-dev/mcdocs/1-ModAPI/接口/通用/索引.html",
    wzm: "网易MC后台",
    gl: "1",
    qz: 1,
    bz: "",
  },
  { wz: "https://www.bilibili.com/", wzm: "b站", gl: "1", qz: 2, bz: "" },
  {
    wz: "https://fanyi.baidu.com/translate",
    wzm: "百度翻译",
    gl: "1",
    qz: 3,
    bz: "",
  },
  {
    wz: "https://pan-yz.chaoxing.com/computerFiles/check_key/",
    wzm: "云盘",
    gl: "1",
    qz: 4,
    bz: "",
  },
  {
    wz: "https://docs.qq.com/desktop",
    wzm: "腾讯文档",
    gl: "1",
    qz: 5,
    bz: "",
  },
  { wz: "https://www.mcmod.cn/", wzm: "MC百科", gl: "1", qz: 6, bz: "" },
  {
    wz: "https://wiki.biligame.com/mc/Minecraft_Wiki",
    wzm: "MC WIKI",
    gl: "1",
    qz: 7,
    bz: "",
  },
  {
    wz: "https://learn.microsoft.com/en-us/minecraft/creator/reference/content/molangreference",
    wzm: "Molang",
    gl: "1",
    qz: 8,
    bz: "",
  },
  {
    wz: "https://learn.microsoft.com/zh-cn/minecraft/creator/reference/content/entityreference/",
    wzm: "Entity JSON",
    gl: "1",
    qz: 9,
    bz: "",
  },
  {
    wz: "https://minecraft.fandom.com/zh/wiki/教程/自定义方块",
    wzm: "Block Wiki",
    gl: "1",
    qz: 10,
    bz: "",
  },
  { wz: "https://mcpedl.com/", wzm: "MCPEDL免费模组", gl: "1", qz: 11, bz: "" },
  {
    wz: "https://www.uuid.online/",
    wzm: "UUID Online",
    gl: "1",
    qz: 12,
    bz: "",
  },
  {
    wz: "https://3dt.easecation.net/",
    wzm: "生成立方3D文本",
    gl: "1",
    qz: 13,
    bz: "",
  },
  {
    wz: "https://bedrock.dev/docs/stable/Entities",
    wzm: "基岩实体文档",
    gl: "1",
    qz: 14,
    bz: "",
  },

  // 3D模型
  {
    wz: "https://app.spline.design/home",
    wzm: "Spline建模",
    gl: "2",
    qz: 1,
    bz: "",
  },
  {
    wz: "https://alpha.womp.com/discover",
    wzm: "Womp免费3D软件",
    gl: "2",
    qz: 2,
    bz: "",
  },
  {
    wz: "https://www.vectary.com/",
    wzm: "Vectary在线3D",
    gl: "2",
    qz: 3,
    bz: "",
  },
  {
    wz: "http://www.3dwhere.com/models",
    wzm: "地委模型STL",
    gl: "2",
    qz: 4,
    bz: "",
  },
  {
    wz: "http://www.mohou.com/moxingku",
    wzm: "魔猴子STL",
    gl: "2",
    qz: 5,
    bz: "",
  },
  {
    wz: "https://www.wenext.cn/print",
    wzm: "未来工场",
    gl: "2",
    qz: 6,
    bz: "",
  },
  {
    wz: "https://www.myminifactory.com",
    wzm: "MyMiniFactory",
    gl: "2",
    qz: 7,
    bz: "",
  },

  // 游戏
  {
    wz: "https://denq04.github.io/ncms/downloads/",
    wzm: "世界盒子ncms",
    gl: "3",
    qz: 1,
    bz: "",
  },
  {
    wz: "https://gamebanana.com/mods",
    wzm: "世界盒子mod",
    gl: "3",
    qz: 2,
    bz: "",
  },
  { wz: "https://petpalsgame.com", wzm: "网游PetPals", gl: "3", qz: 3, bz: "" },
  {
    wz: "http://emojisandearthporn.com/",
    wzm: "Emojis & Earth Porn",
    gl: "3",
    qz: 4,
    bz: "",
  },
  {
    wz: "http://jspvz.com/download.htm",
    wzm: "植物僵尸相关下载",
    gl: "3",
    qz: 5,
    bz: "",
  },
  {
    wz: "https://yandex.com/games",
    wzm: "Yandex免费在线游戏",
    gl: "3",
    qz: 6,
    bz: "",
  },
  {
    wz: "https://www.cslbbs.net/",
    wzm: "都市天际线2中文论坛",
    gl: "3",
    qz: 7,
    bz: "",
  },
  { wz: "https://www.gamer520.com/", wzm: "破解游戏", gl: "3", qz: 8, bz: "" },
  { wz: "https://itch.io/", wzm: "游戏网站 itch.io", gl: "3", qz: 9, bz: "" },
  {
    wz: "https://bbk.endyun.ltd/download",
    wzm: "mc国际版下载",
    gl: "3",
    qz: 10,
    bz: "",
  },
  {
    wz: "https://www.nexusmods.com/",
    wzm: "Nexus游戏模组市场",
    gl: "3",
    qz: 11,
    bz: "",
  },
  {
    wz: "https://9mod.com/download",
    wzm: "破解安卓游戏",
    gl: "3",
    qz: 12,
    bz: "",
  },
  {
    wz: "https://happybabys.cn/Client.html",
    wzm: "开心宝贝",
    gl: "3",
    qz: 13,
    bz: "",
  },
  {
    wz: "https://play.mc.js.cool/1.8/",
    wzm: "MC网页版1.8",
    gl: "3",
    qz: 14,
    bz: "",
  },

  // 实用工具
  {
    wz: "https://www.gaitubao.com/yinzhang/",
    wzm: "在线生成印章工具",
    gl: "4",
    qz: 1,
    bz: "",
  },
  {
    wz: "https://chunker.app/",
    wzm: "MC存档转换Chunker",
    gl: "4",
    qz: 2,
    bz: "",
  },
  {
    wz: "https://chatglm.cn/main/detail",
    wzm: "智谱清言",
    gl: "4",
    qz: 3,
    bz: "",
  },
  {
    wz: "https://www.toolhelper.cn/Image/ImageToIco",
    wzm: "图片转ico在线工具",
    gl: "4",
    qz: 4,
    bz: "",
  },
  {
    wz: "https://app.flourish.studio/projects",
    wzm: "数据可视化",
    gl: "4",
    qz: 5,
    bz: "",
  },
  {
    wz: "http://bbs.bathome.net/thread-75-1-1.html",
    wzm: "BAT教程-批处理",
    gl: "4",
    qz: 6,
    bz: "",
  },
  {
    wz: "https://smallpdf.com/cn/pdf-to-jpg",
    wzm: "PDF转JPG",
    gl: "4",
    qz: 7,
    bz: "",
  },
  {
    wz: "https://www.ilovepdf.com/zh-cn/split_pdf",
    wzm: "在线拆分PDF",
    gl: "4",
    qz: 8,
    bz: "",
  },
  { wz: "https://www.chiplot.online/", wzm: "ChiPlot", gl: "4", qz: 9, bz: "" },
  {
    wz: "https://www.sucj.me/index.php/archives/16287/",
    wzm: "草图大师免费插件",
    gl: "4",
    qz: 10,
    bz: "",
  },
  {
    wz: "https://js.design/workspace",
    wzm: "即时设计",
    gl: "4",
    qz: 11,
    bz: "",
  },
  {
    wz: "https://boardmix.cn/app/home",
    wzm: "boardmix",
    gl: "4",
    qz: 12,
    bz: "",
  },
  {
    wz: "https://mail.163.com/js6/main.jsp",
    wzm: "网易邮箱6.0版",
    gl: "4",
    qz: 13,
    bz: "",
  },
  {
    wz: "https://www.transparenttextures.com/",
    wzm: "透明纹理",
    gl: "4",
    qz: 14,
    bz: "",
  },
  {
    wz: "https://www.pixilart.com/",
    wzm: "Pixilart在线像素绘制",
    gl: "4",
    qz: 15,
    bz: "",
  },
  {
    wz: "https://tg-image.com/",
    wzm: "TG Image免费图床",
    gl: "4",
    qz: 16,
    bz: "",
  },
  {
    wz: "https://www.midorg.com/h.html",
    wzm: "Re01 HTML教学小工具",
    gl: "4",
    qz: 17,
    bz: "",
  },
  {
    wz: "https://tinypng.com/",
    wzm: "TinyPNG图片转换压缩",
    gl: "4",
    qz: 18,
    bz: "",
  },
  {
    wz: "https://fmg.8desk.top/",
    wzm: "Azgaar奇幻地图生成器",
    gl: "4",
    qz: 19,
    bz: "",
  },
  { wz: "https://suno.com/", wzm: "Suno", gl: "4", qz: 20, bz: "" },
  { wz: "https://drive.uc.cn/list", wzm: "UC网盘", gl: "4", qz: 21, bz: "" },
  {
    wz: "https://developer.mozilla.org/zh-CN/docs/Web/HTML",
    wzm: "HTML文档 | MDN",
    gl: "4",
    qz: 22,
    bz: "",
  },
  {
    wz: "https://developer.mozilla.org/zh-CN/play",
    wzm: "Html运行 | MDN",
    gl: "4",
    qz: 23,
    bz: "",
  },
  {
    wz: "https://codepen.io/",
    wzm: "HTML*CodePen社区",
    gl: "4",
    qz: 24,
    bz: "",
  },
  { wz: "http://m.161959.com/#", wzm: "尺子在线测量", gl: "4", qz: 25, bz: "" },
  {
    wz: "https://css.bqrdh.com/safety-color",
    wzm: "Web安全色 | CSS可视化",
    gl: "4",
    qz: 26,
    bz: "",
  },
  { wz: "https://www.bqrdh.com/", wzm: "不求人导航", gl: "4", qz: 27, bz: "" },
  {
    wz: "https://mirrors.huaweicloud.com/python/",
    wzm: "python国内镜像下载",
    gl: "4",
    qz: 28,
    bz: "",
  },
  {
    wz: "https://www.yuque.com/baicaigongchang1145haoyuangong/ib3g1e/dkxgpiy9zb96hob4",
    wzm: "Ai语言克隆GPT sovits",
    gl: "4",
    qz: 29,
    bz: "",
  },
  {
    wz: "https://gsv.acgnai.top/",
    wzm: "在线Ai语音合成",
    gl: "4",
    qz: 30,
    bz: "",
  },
  {
    wz: "https://hf-mirror.com/THUDM/CogVideoX1.5-5B-SAT",
    wzm: "THUDM/CogVideoX1.5-5B-SAT",
    gl: "4",
    qz: 31,
    bz: "",
  },
  {
    wz: "https://www.qqxiuzi.cn/zh/pinyin-zhuyin.php",
    wzm: "注音符转换",
    gl: "4",
    qz: 32,
    bz: "",
  },
  {
    wz: "https://www.lookae.com/after-effects/aechajian/",
    wzm: "AE插件",
    gl: "4",
    qz: 33,
    bz: "",
  },
  {
    wz: "https://www.kdocs.cn/latest",
    wzm: "WPS云文档",
    gl: "4",
    qz: 34,
    bz: "",
  },
  {
    wz: "https://www.feejii.com/console/files",
    wzm: "小飞机网盘",
    gl: "4",
    qz: 35,
    bz: "",
  },
  { wz: "https://6-u.com/", wzm: "乐游导航", gl: "4", qz: 36, bz: "" },
  {
    wz: "https://chat.deepseek.com/",
    wzm: "腾讯元宝",
    gl: "4",
    qz: 37,
    bz: "",
  },
  {
    wz: "https://cloud.189.cn/web/main/file",
    wzm: "天翼云盘",
    gl: "4",
    qz: 38,
    bz: "",
  },
  {
    wz: "https://ytdownfk.com/zh-cn/",
    wzm: "ytdownfk",
    gl: "4",
    qz: 39,
    bz: "",
  },
  {
    wz: "https://3g.gljlw.com/diy/douyin.php",
    wzm: "在线提取抖因",
    gl: "4",
    qz: 40,
    bz: "",
  },
  {
    wz: "https://vpcs.fanyu.com/",
    wzm: "维普论文检测",
    gl: "4",
    qz: 41,
    bz: "",
  },
  {
    wz: "https://www.paperyy.com/member_new/thesis/post.aspx",
    wzm: "PaperYY论文查重",
    gl: "4",
    qz: 42,
    bz: "",
  },
  {
    wz: "https://kuaipaper.com/rewrite",
    wzm: "SpeedAI科研小助手",
    gl: "4",
    qz: 43,
    bz: "",
  },
  {
    wz: "https://pangdaxing.top/Adobe/",
    wzm: "Adobe破解版下载",
    gl: "4",
    qz: 44,
    bz: "",
  },
  { wz: "https://dayone.me/all", wzm: "Day One", gl: "4", qz: 45, bz: "" },
  {
    wz: "https://www.iloveimg.com/zh-cn/html-to-image",
    wzm: "HTML转图片工具",
    gl: "4",
    qz: 46,
    bz: "",
  },
  {
    wz: "https://lmarena.ai/c/5b8b6aca-d79c-4438-8bd4-18ce65779c9b",
    wzm: "LMArena",
    gl: "4",
    qz: 47,
    bz: "",
  },
  {
    wz: "https://fmhy.net/",
    wzm: "资源下载freemediaheckyeah",
    gl: "4",
    qz: 48,
    bz: "",
  },
  {
    wz: "https://aistudio.google.com/prompts/new_chat",
    wzm: "Google AI Studio",
    gl: "4",
    qz: 49,
    bz: "",
  },
  {
    wz: "https://imgchr.com/ringo2794",
    wzm: "免费图床",
    gl: "4",
    qz: 50,
    bz: "",
  },
  {
    wz: "https://ai.meta.com/sam3d/",
    wzm: "Sam生成3D模型",
    gl: "4",
    qz: 51,
    bz: "",
  },

  // 投稿
  { wz: "https://www.5iidea.com/", wzm: "创意星球", gl: "5", qz: 1, bz: "" },
  {
    wz: "https://cc.moocollege.com/#/details/worksShow?id=19185",
    wzm: "摩课云-竞赛平台",
    gl: "5",
    qz: 2,
    bz: "",
  },
  {
    wz: "https://www.ncda.org.cn/",
    wzm: "未来设计师NCDA",
    gl: "5",
    qz: 3,
    bz: "",
  },
  {
    wz: "https://dasai.lanqiao.cn/",
    wzm: "蓝桥杯大赛",
    gl: "5",
    qz: 4,
    bz: "",
  },
  {
    wz: "http://www.huacanjiang.com/home",
    wzm: "华灿奖",
    gl: "5",
    qz: 5,
    bz: "",
  },
  {
    wz: "https://cc.moocollege.com/#/details?id=23995",
    wzm: "华灿-摩课云",
    gl: "5",
    qz: 6,
    bz: "",
  },
  {
    wz: "https://www.kejiaofun.com/act-blue",
    wzm: "大广赛",
    gl: "5",
    qz: 7,
    bz: "",
  },
  {
    wz: "https://www.sun-ada.net/home.html",
    wzm: "大广赛",
    gl: "5",
    qz: 8,
    bz: "",
  },

  // 美术
  {
    wz: "https://www.yswgame.com/",
    wzm: "像素素材下载",
    gl: "6",
    qz: 1,
    bz: "",
  },
  {
    wz: "https://www.ikea.cn/cn/zh/",
    wzm: "宜家家居官网",
    gl: "6",
    qz: 2,
    bz: "",
  },
  {
    wz: "http://3dviewer.bimant.com/index.html",
    wzm: "3D模型在线查看器",
    gl: "6",
    qz: 3,
    bz: "",
  },
  {
    wz: "https://unsplash.com/",
    wzm: "Unsplash无版权图片",
    gl: "6",
    qz: 4,
    bz: "",
  },
  {
    wz: "https://pixabay.com/",
    wzm: "Pixabay无版权可中文搜",
    gl: "6",
    qz: 5,
    bz: "",
  },
  {
    wz: "https://www.pexels.com/zh-cn/",
    wzm: "pexels无版权图片",
    gl: "6",
    qz: 6,
    bz: "",
  },
  {
    wz: "https://pngimg.com/search_image",
    wzm: "免扣PNG",
    gl: "6",
    qz: 7,
    bz: "",
  },
  {
    wz: "https://stocksnap.io/search/wallpaper+background",
    wzm: "超级壁纸背景",
    gl: "6",
    qz: 8,
    bz: "",
  },
  {
    wz: "https://www.tuozhe8.com/plugin.php",
    wzm: "室内设计灵感图库",
    gl: "6",
    qz: 9,
    bz: "",
  },
  {
    wz: "https://www.archiproducts.com/zh/产品/ethimo/椅子-grand-life_673839",
    wzm: "GRAND LIFE椅子",
    gl: "6",
    qz: 10,
    bz: "",
  },
  { wz: "http://www.fnji.net/", wzm: "梵几家具", gl: "6", qz: 11, bz: "" },
  {
    wz: "https://mumolife.jiyoujia.com/category-413725925.htm",
    wzm: "桌-MUMO木墨",
    gl: "6",
    qz: 12,
    bz: "",
  },
  {
    wz: "https://tooblack.jiyoujia.com/shop/view_shop.htm",
    wzm: "二黑木作",
    gl: "6",
    qz: 13,
    bz: "",
  },
  {
    wz: "https://thefunhouse.jiyoujia.com/shop/view_shop.htm",
    wzm: "凡屋家具",
    gl: "6",
    qz: 14,
    bz: "",
  },
  {
    wz: "https://www.zcool.com.cn/discover",
    wzm: "站酷ZCOOL",
    gl: "6",
    qz: 15,
    bz: "",
  },
  {
    wz: "https://www.figma.com/files/project",
    wzm: "Figma",
    gl: "6",
    qz: 16,
    bz: "",
  },
  {
    wz: "https://www.toptal.com/designers/subtlepatterns",
    wzm: "All Tags贴图",
    gl: "6",
    qz: 17,
    bz: "",
  },
  {
    wz: "https://civitai.com/",
    wzm: "Civitai-Ai模型下载",
    gl: "6",
    qz: 18,
    bz: "",
  },
  {
    wz: "https://assetstore.unity.com/",
    wzm: "Unity美术资源商店",
    gl: "6",
    qz: 19,
    bz: "",
  },
  {
    wz: "https://opengameart.org/",
    wzm: "免费游戏美术资源",
    gl: "6",
    qz: 20,
    bz: "",
  },
  {
    wz: "https://dotown.maeda-design-room.net/",
    wzm: "任天堂游戏美术",
    gl: "6",
    qz: 21,
    bz: "",
  },
  {
    wz: "https://spline.design/",
    wzm: "Spline-3D Design",
    gl: "6",
    qz: 22,
    bz: "",
  },
  {
    wz: "https://ambientcg.com/",
    wzm: "免费贴图库ambientCG",
    gl: "6",
    qz: 23,
    bz: "",
  },
  {
    wz: "https://3dassets.one/",
    wzm: "免费模型3Dassets.one",
    gl: "6",
    qz: 24,
    bz: "",
  },
  {
    wz: "https://itch.io/game-assets/tag-3d",
    wzm: "itch.io免费资产",
    gl: "6",
    qz: 25,
    bz: "",
  },
  {
    wz: "https://www.pngall.com/",
    wzm: "免费抠图素材",
    gl: "6",
    qz: 26,
    bz: "",
  },

  // 宣传
  {
    wz: "https://mp.weixin.qq.com/",
    wzm: "微信公众平台",
    gl: "7",
    qz: 1,
    bz: "",
  },
  {
    wz: "https://creator.xiaohongshu.com/creator/notemanage",
    wzm: "小红书创作服务平台",
    gl: "7",
    qz: 2,
    bz: "",
  },
  {
    wz: "https://channels.weixin.qq.com/platform/post/list",
    wzm: "视频号助手",
    gl: "7",
    qz: 3,
    bz: "",
  },
  {
    wz: "https://creator.douyin.com/creator-micro/home",
    wzm: "抖音创作者中心",
    gl: "7",
    qz: 4,
    bz: "",
  },

  {
    wz: "https://tv.cctv.com/2014/07/27/VIDE1406399770522952.shtml",
    wzm: "《武林外传》第1集",
    gl: "8",
    qz: 1,
    bz: "CCTV官方正版",
  },
  {
    wz: "https://www.mayiyingshi.tv/vodplay/121179-1-1.html",
    wzm: "爱情公寓4",
    gl: "8",
    qz: 2,
    bz: "蚂蚁影视",
  },
  {
    wz: "https://www.mayiyingshi.tv/vodplay/62824-1-11.html",
    wzm: "爱情公寓3",
    gl: "8",
    qz: 3,
    bz: "蚂蚁影视",
  },
  {
    wz: "http://www.phjy.com.cn/y/1348-0-29.html",
    wzm: "快乐星球第一部",
    gl: "8",
    qz: 4,
    bz: "樱花动漫",
  },
  {
    wz: "http://www.cnjiean.com/pan/21842/1-1.html",
    wzm: "迷离时空(原版)第四季",
    gl: "8",
    qz: 5,
    bz: "蜗牛影院",
  },
  {
    wz: "https://www.dacaer.com/lvzhengyiwumeiju/DesperateHousewives1-3.html",
    wzm: "绝望的主妇1-3季",
    gl: "8",
    qz: 6,
    bz: "天天美剧",
  },
  {
    wz: "https://www.dacaer.com/xijumeiju/DesperateHousewives4-6.html",
    wzm: "绝望的主妇4-6季",
    gl: "8",
    qz: 7,
    bz: "天天美剧",
  },
  {
    wz: "https://www.sjsti.com/view/milishikongyuanbandisiji/683953c0d8def.html",
    wzm: "迷离时空第四季",
    gl: "8",
    qz: 8,
    bz: "追剧网",
  },
  {
    wz: "https://vidhub4.cc/vodplay/242901-1-1.html",
    wzm: "迷离时空原版第五季",
    gl: "8",
    qz: 9,
    bz: "Vidhub",
  },

  // 开发工具
  {
    wz: "https://github.com/",
    wzm: "GitHub",
    gl: "9",
    qz: 1,
    bz: "全球最大代码托管",
  },
  {
    wz: "https://rxeditor.vercel.app/ui-designer/admin/modules",
    wzm: "RxDrag低代码",
    gl: "9",
    qz: 2,
    bz: "可视化开发",
  },
  {
    wz: "https://vular.cn/rxeditor/",
    wzm: "RXEditor",
    gl: "9",
    qz: 3,
    bz: "国产低代码",
  },
  {
    wz: "https://cloudstudio.net/u/284493",
    wzm: "云代码CloudStudio",
    gl: "9",
    qz: 4,
    bz: "腾讯云在线IDE",
  },
  {
    wz: "https://vscode.dev/",
    wzm: "VS Code工作区",
    gl: "9",
    qz: 5,
    bz: "浏览器版VS Code",
  },
  {
    wz: "https://gamemaker.weixin.qq.com/ide",
    wzm: "微信小游戏制作工具",
    gl: "9",
    qz: 6,
    bz: "腾讯小游戏IDE",
  },

  // 教育资源
  {
    wz: "https://www.runoob.com/html/html-tutorial.html",
    wzm: "菜鸟HTML教程",
    gl: "10",
    qz: 1,
    bz: "前端入门",
  },
  {
    wz: "https://layout.bradwoods.io/",
    wzm: "CSS生成器",
    gl: "10",
    qz: 2,
    bz: "布局可视化",
  },
  {
    wz: "https://www.bilibili.com/video/BV1jc411k7Mj",
    wzm: "Godot4中文教程",
    gl: "10",
    qz: 3,
    bz: "B站视频",
  },
  {
    wz: "https://cn.eagle.cool/blog/post/free-game-assets",
    wzm: "免费游戏素材",
    gl: "10",
    qz: 4,
    bz: "2D/3D资源",
  },
  {
    wz: "https://xiaokang2022.github.io/tkintertools-docs/2.6/",
    wzm: "tkintertools文档",
    gl: "10",
    qz: 5,
    bz: "Python GUI",
  },

  // 云与空间
  {
    wz: "https://cloud.huawei.com/home",
    wzm: "华为云空间",
    gl: "11",
    qz: 1,
    bz: "华为云盘",
  },

  // 学术与论文
  {
    wz: "https://ac.scmor.com/",
    wzm: "思谋学术",
    gl: "12",
    qz: 1,
    bz: "谷歌学术镜像",
  },
  {
    wz: "https://vgms.fanyu.com/admin/index",
    wzm: "维普毕业设计系统",
    gl: "12",
    qz: 2,
    bz: "维普毕设",
  },
  {
    wz: "https://hf-mirror.com/ystemsrx/Qwen2-Boundless",
    wzm: "Qwen2-Boundless模型",
    gl: "12",
    qz: 3,
    bz: " HuggingFace镜像",
  },
  {
    wz: "https://www.modelscope.cn/models/QuantFactory/Qwen2-Boundless-GGUF",
    wzm: "Qwen2-Boundless-GGUF",
    gl: "12",
    qz: 4,
    bz: "ModelScope",
  },
  {
    wz: "https://www.wjx.cn/newwjx/manage/myquestionnaires.aspx",
    wzm: "问卷星(免费版)",
    gl: "12",
    qz: 5,
    bz: "在线问卷",
  },
  {
    wz: "https://www.gocheck.cn/loginAction/toMain.do",
    wzm: "格子达论文检测",
    gl: "12",
    qz: 6,
    bz: "论文查重",
  },
];
