// data.js - 标签页配置文件（手动修改增删）

// 1. 归类字典（分类配置）
window.categoryConfig = [
  { glm: "常用工具", dh: "e", qz: 1 },
  { glm: "社交娱乐", dh: "d", qz: 2 },
  { glm: "学习资料", dh: "a", qz: 3 },
  { glm: "办公协作", dh: "b", qz: 4 },
  { glm: "购物消费", dh: "c", qz: 5 },
];

window.siteConfig = [
  { wzm: "百度", wz: "https://www.baidu.com ", gl: "e", qz: 1 },
  { wzm: "必应", wz: "https://cn.bing.com ", gl: "e", qz: 2 },
  { wzm: "在线计算器", wz: "https://www.calculator.net ", gl: "e", qz: 3 },
  { wzm: "截图工具", wz: "https://www.snipaste.com ", gl: "e", qz: 4 },
  
  { wzm: "S", wz: "https://cn.bin01g.com ", gl: "e", qz: 4 },
  { wzm: "K", wz: "https://cn.bi14ng.com ", gl: "e", qz: 4 },
  { wzm: "Loooooooo", wz: "https://cn.bin585g.com ", gl: "e", qz: 4 },
  { wzm: "R", wz: "https://cn.bi74ng.com ", gl: "e", qz: 4 },
  { wzm: "W", wz: "https://cn.bi585ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "S", wz: "https://cn.bin01g.com ", gl: "e", qz: 4 },
  { wzm: "K", wz: "https://cn.bi14ng.com ", gl: "e", qz: 4 },
  { wzm: "L", wz: "https://cn.bin585g.com ", gl: "e", qz: 4 },
  { wzm: "R", wz: "https://cn.bi74ng.com ", gl: "e", qz: 4 },
  { wzm: "W", wz: "https://cn.bi585ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "S", wz: "https://cn.bin01g.com ", gl: "e", qz: 4 },
  { wzm: "K", wz: "https://cn.bi14ng.com ", gl: "e", qz: 4 },
  { wzm: "L", wz: "https://cn.bin585g.com ", gl: "e", qz: 4 },
  { wzm: "R", wz: "https://cn.bi74ng.com ", gl: "e", qz: 4 },
  { wzm: "W", wz: "https://cn.bi585ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "S", wz: "https://cn.bin01g.com ", gl: "e", qz: 4 },
  { wzm: "K", wz: "https://cn.bi14ng.com ", gl: "e", qz: 4 },
  { wzm: "L", wz: "https://cn.bin585g.com ", gl: "e", qz: 4 },
  { wzm: "R", wz: "https://cn.bi74ng.com ", gl: "e", qz: 4 },
  { wzm: "W", wz: "https://cn.bi585ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "S", wz: "https://cn.bin01g.com ", gl: "e", qz: 4 },
  { wzm: "K", wz: "https://cn.bi14ng.com ", gl: "e", qz: 4 },
  { wzm: "L", wz: "https://cn.bin585g.com ", gl: "e", qz: 4 },
  { wzm: "R", wz: "https://cn.bi74ng.com ", gl: "e", qz: 4 },
  { wzm: "W", wz: "https://cn.bi585ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  { wzm: "BK", wz: "https://cn.b3338ng.com ", gl: "e", qz: 4 },
  

  { wzm: "微信网页版", wz: "https://wx.qq.com ", gl: "d", qz: 1 },
  { wzm: "抖音网页版", wz: "https://www.douyin.com ", gl: "d", qz: 2 },
  { wzm: "B站", wz: "https://www.bilibili.com ", gl: "d", qz: 3 },

  { wzm: "MDN文档", wz: "https://developer.mozilla.org ", gl: "a", qz: 1 },
  { wzm: "菜鸟教程", wz: "https://www.runoob.com ", gl: "a", qz: 2 },
  { wzm: "GitHub", wz: "https://github.com ", gl: "a", qz: 3 },

  { wzm: "腾讯文档", wz: "https://docs.qq.com ", gl: "b", qz: 1 },
  { wzm: "飞书", wz: "https://www.feishu.cn ", gl: "b", qz: 2 },

  { wzm: "淘宝", wz: "https://www.taobao.com ", gl: "c", qz: 1 },
  { wzm: "京东", wz: "https://www.jd.com ", gl: "c", qz: 2 },
];

// 3. 首字典（预留，暂为空）
window.firstConfig = [];
