// res_wall.js 楼栋建筑立面贴图

const IMAGES = [
	{
		name: "类型1",
		data: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAQCAYAAACm53kpAAAAAXNSR0IArs4c6QAAAIFJREFUWIVj3LFnz3+GEQxYBAQEBtoNAwpYYIwPHz5gSMICB5/cUNfPgiy4acMGONsvIICBWLmhrJ8Jq0kjCIwGwEA7YKAB44kzZ0Z0NTjiUwBKNbhk0SK4RExcHEo1gktuqOsf8SlgNAAG2gEDDeC1wFBtylKqf8RXgyzYQmckAQCtJYhzEtBvnAAAAABJRU5ErkJggg=="
	},
	{
		name: "类型2",
		data: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAQCAYAAACm53kpAAAAAXNSR0IArs4c6QAAAHpJREFUWIVj3LFnz3+GEQxYBAQEBtoNAwpYYIwPHz6QpBE94IaqfhZkwU0bNhCl2S8gAKv4UNTPRJSOYQxGfAAwnjhz5j8Dw9DNw5TqhwfASAUjPguMVoPIgksWLSJKc0xcHFbxoah/xGeBER8Ao9XgSK8GWUgNueEGAN1nW9PUJTPYAAAAAElFTkSuQmCC"
	},
	{
		name: "类型3",
		data: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAQCAYAAACm53kpAAAAAXNSR0IArs4c6QAAAIhJREFUWIVj3LFnz3+GEQxYBAQEBtoNAwqYBtoBAw1YGBgYGD58+ECWZljqGcr6WWCcJYsWkaQ5Ji4Ohb9pwwaS9PsFBKDwB8r+EZ8FRgNgoB0w0GA0AAbaAQMNRgNgoB0w0ICFsBLiwKdPn6hlFF3tH/EpgPHEmTP/h3JTllL9jCfOnBnR3WEA3dAz76wC/4EAAAAASUVORK5CYII="
	},
	{
		name: "类型4",
		data: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAQCAYAAACm53kpAAAAAXNSR0IArs4c6QAAAH1JREFUWIVj3LFnz3+GEQxYBAQEBtoNAwqYBtoBAw1YGBgYGD58+ECWZljqGcr6WWCcTRs2YCjwCwggKDfU9Y/4LDAaAAPtgIEGowEw0A4YaDAaAAPtgIEG8HbAp0+fcCrCJzfU9Y/4FMB44syZ/0O5KUupfsYTZ86M6O4wAB9QUPPTvDjCAAAAAElFTkSuQmCC"
	},
	{
		name: "类型5",
		data: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAQCAYAAACm53kpAAAAAXNSR0IArs4c6QAAAHtJREFUWIXtlrENwCAMBJ+IATxZxKgoVQoGoPAwlhcgRUQGIIWF7OsoHr0sv97pbm3AMZmIrD2YclgbsCYDgIgsief27KzP83HVuvTJrpylAIgIxAC+CKiqpQ8zUmd2fQdEBIC3Rjy2ABHFBrgfQLRAZx47n7J/9e5r8AFrXzRRmaghawAAAABJRU5ErkJggg=="
	},
	{
		name: "类型6",
		data: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAQCAYAAACm53kpAAAAAXNSR0IArs4c6QAAAIFJREFUWIVjPHHmzH+GEQyYBtoBAw1YkDkfPnyAswUEBBiIlRvK+pnQFWzasAFDAz65oa4fJQvAFMBoYuWGsv4RXwaMBsBAO2CgwWgADLQDBhqMBgAy59OnTyg0sXJDWT9GCiDGAnxgqOlnhHWGsLWuYE1GfHIwMFT1M472Bkc4AAASl9z9yBqZjAAAAABJRU5ErkJggg=="
	},
	{
		name: "类型7",
		data: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAQCAYAAACm53kpAAAAAXNSR0IArs4c6QAAAKJJREFUWIXtl0EKgCAQRadoLXOy6ADh4aIDRKdo4WE+XqBWQWJWthmm/DALlYefD8pMtTi3AiBmphwdGc18nUV9UE3qAECwfpOwBv40AAA0DkOw11v72IQmPnoCO2yMCWqepijVq8u18L//A0oA0gakVQKQNiCtEoC0AWlFATAz9daS9z6otuseNSLa+Co1DN21knfDiBY+OQvk9t5a+d//ARuzdsejHdBYJAAAAABJRU5ErkJggg=="
	},
]; 
