// res_wall.js 楼栋建筑立面贴图

const IMAGES = [
	{
		name: "类型1",
		data: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAQCAYAAACm53kpAAAAAXNSR0IArs4c6QAAAHZJREFUWIVj/Pzjx3+GEQyYBtoBAw1YYIxPnz5hSPLx8RGUG+r6WZAFL164AGfrGxgwECs3lPWP+CwwGgAD7YCBBoyj1eAIByjV4Pq1a+ESgcHBKNUILrmhrn/Ep4DRABhoBww0gNcCQ7UpS6n+0WpwoB0w0AAAkUaHq2TE8NAAAAAASUVORK5CYII="
	},
	{
		name: "类型2",
		data: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAQCAYAAACm53kpAAAAAXNSR0IArs4c6QAAAG1JREFUWIVj/Pzjx3+GEQyYBtoBAw1YYIxPnz6RpJGPjw+FP1T1syALXrxwgSjN+gYGWMWHov4RnwVGfAAwwmqBoZqHKdXPOFoNjnAwWg0iC65fu5YozYHBwVjFh6L+EZ8FRnwAjFaDo9XgCAcACrlbjmI5GSQAAAAASUVORK5CYII="
	},
	{
		name: "类型3",
		data: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAQCAYAAACm53kpAAAAAXNSR0IArs4c6QAAAINJREFUWIVj/Pzjx3+GEQyYBtoBAw1GfACwMDAwMHz69IkszXx8fAxDXT8LjLN+7VqSNAcGB6PwL164QJJ+fQMDFP5A2T/is8BoAAy0AwYajAbAQDtgoMFoAAy0AwYasBBWQhy4d/cuSerR2wEDZf+ITwGMn3/8+D+Um7KU6mcc6d1hAOhONhhOf6t4AAAAAElFTkSuQmCC"
	},
	{
		name: "类型4",
		data: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAQCAYAAACm53kpAAAAAXNSR0IArs4c6QAAAHpJREFUWIVjfPrq1X+GEQwYP//4MaIDgGmgHTDQgIWBgYHh06dPZGnm4+NjGOr6WWCcixcuYCjQNzAgKDfU9Y/4LDAaAAPtgIEGowEw0A4YaDDiAwBeDd67exdDElZV4JMb6vpHfAoY8QHA+PnHj/9DuSlLqf4R3xsEAO4JWLmDotreAAAAAElFTkSuQmCC"
	},
	{
		name: "类型5",
		data: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAQCAYAAACm53kpAAAAAXNSR0IArs4c6QAAAHJJREFUWIXtlrENwCAMBJ8otVcJ+09BBiBdGkrTuIMiCiPwhX0TnF5+vdPb2oBjUjdzHcDBFmBzAoCqsj0oiMgXAADcpTBdtnPlDCAqEAGsCjy1Mj2281cgZpAtwGbNoMcVEJG4APcBxAp0s+H5FXY/gxNvDyi0Y5uFMQAAAABJRU5ErkJggg=="
	},
	{
		name: "类型6",
		data: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAQCAYAAACm53kpAAAAAXNSR0IArs4c6QAAAIBJREFUWIXtVzEOwCAIFNOZ/z/LPsA+gi5u7YTR2hg2QuAWJMcFQtQA3K09yTGydgHaOEaHiPoZEZOUs6zP34CzlEWw46zrpyfAAWylnGW9+z8gGqBdgDaiAdoFaCMaMDpXrZOVcpb1yw2QJNjBmh54Gfqbrnhk3HEMq3qIbdA5XhiI4f7rXYYWAAAAAElFTkSuQmCC"
	},
	{
		name: "类型7",
		data: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAQCAYAAACm53kpAAAAAXNSR0IArs4c6QAAAJtJREFUWIXtlzEOgCAMRdE4cwg5gFzFcE7iVfQq34VNJxKJgODSVPkbLS/5+UPTdrtzBwAhpRQ1ujKc+b6K+qCGVANA8H6TMAc+GgAAsVgb1GZjik1w4m8BeHhUKqhv6yomrR9NcON/PwNaANQGqNUCoDZArRYAtQFqdbFboGSRyO3inPhoAP7DVbF+7hjhwidvgdrdmyv/+xlwAnDUvjhj3zWwAAAAAElFTkSuQmCC"
	},
]; 
