// res_wall.js 楼栋建筑立面贴图

const IMAGES = [
	{
		name: "类型1",
		data: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAQCAYAAACm53kpAAAAAXNSR0IArs4c6QAAAHZJREFUWIVj/Pzjx3+GEQyYBtoBAw1YYIxPnz5hSPLx8RGUG+r6WZAFL164AGfrGxgwECs3lPWP+CwwGgAD7YCBBoyj1eAIByjV4Pq1a+ESgcHBKNUILrmhrn/Ep4DRABhoBww0gNcCQ7UpS6n+0WpwoB0w0AAAkUaHq2TE8NAAAAAASUVORK5CYII="
	},
	{
		name: "类型2",
		data: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAQCAYAAACm53kpAAAAAXNSR0IArs4c6QAAAG1JREFUWIVj/Pzjx3+GEQyYBtoBAw1YYIxPnz6RpJGPjw+FP1T1syALXrxwgSjN+gYGWMWHov4RnwVGfAAwwmqBoZqHKdXPOFoNjnAwWg0iC65fu5YozYHBwVjFh6L+EZ8FRnwAjFaDo9XgCAcACrlbjmI5GSQAAAAASUVORK5CYII="
	},
	{
		name: "类型3",
		data: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAQCAYAAACm53kpAAAAAXNSR0IArs4c6QAAAIRJREFUWIVj/Pzjx3+GEQxYGBgYGD59+kSWZj4+Poahrp8Fxlm/di1JmgODg1H4Fy9cIEm/voEBCn+g7GciSdcwBKMBMNAOGGgwGgAD7YCBBqMBMNAOGGgwGgAD7YCBBiyElRAH7t29S5J69JbgQNk/4lMA4+cfP/4P5c4MpfoZR3p3GAAjNTYY7nrZLwAAAABJRU5ErkJggg=="
	},
	{
		name: "类型4",
		data: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAQCAYAAACm53kpAAAAAXNSR0IArs4c6QAAAHpJREFUWIVjfPrq1X+GEQwYP//4MaIDgGmgHTDQgIWBgYHh06dPZGnm4+NjGOr6WWCcixcuYCjQNzAgKDfU9Y/4LDAaAAPtgIEGowEw0A4YaDDiAwBeDd67exdDElZV4JMb6vpHfAoY8QHA+PnHj/9DuSlLqf4R3xsEAO4JWLmDotreAAAAAElFTkSuQmCC"
	},
	{
		name: "类型5",
		data: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAQCAYAAACm53kpAAAAAXNSR0IArs4c6QAAAFJJREFUWIXtlrENACAMwyjq/0fBHbCxsLKwwRkeEl9gRZXqOPe+IkylBWiyt0Y7oMhfgAegBWhyjkE7oMTaW/oNhjtAHHcALUDjAWgBGneAegd87I4ZFyhlYJkAAAAASUVORK5CYII="
	},
	{
		name: "类型6",
		data: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAQCAYAAACm53kpAAAAAXNSR0IArs4c6QAAAIBJREFUWIXtVzEOwCAIFNOZ/z/LPsA+gi5u7YTR2hg2QuAWJMcFQtQA3K09yTGydgHaOEaHiPoZEZOUs6zP34CzlEWw46zrpyfAAWylnGW9+z8gGqBdgDaiAdoFaCMaMDpXrZOVcpb1yw2QJNjBmh54Gfqbrnhk3HEMq3qIbdA5XhiI4f7rXYYWAAAAAElFTkSuQmCC"
	},
	{
		name: "类型7",
		data: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAQCAYAAACm53kpAAAAAXNSR0IArs4c6QAAAJtJREFUWIXtlzEOgCAMRdE4cwg5gFzFcE7iVfQq34VNJxKJgODSVPkbLS/5+UPTdrtzBwAhpRQ1ujKc+b6K+qCGVANA8H6TMAc+GgAAsVgb1GZjik1w4m8BeHhUKqhv6yomrR9NcON/PwNaANQGqNUCoDZArRYAtQFqdbFboGSRyO3inPhoAP7DVbF+7hjhwidvgdrdmyv/+xlwAnDUvjhj3zWwAAAAAElFTkSuQmCC"
	},
	{
		name: "类型8",
		data: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAQCAYAAACm53kpAAAAAXNSR0IArs4c6QAAAGtJREFUWIXtkLENgDAMBB9E7VXIKihzRqwSVjFNulBRIHc0ryh/nWVbOt1yt9bdHX8wMwDAyP/bO1y1hoM9JQDAWUrYHTl/5lH/17CZDAVgC7BRALYAGwVgC7BRALYAGwVgC7BRALYAm+kDPCgeKAQ3FoXaAAAAAElFTkSuQmCC"
	},
	{
		name: "类型9",
		data: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAQCAYAAACm53kpAAAAAXNSR0IArs4c6QAAAHVJREFUWIVj/Pzjx/9Pnz4xkAP4+PgYGBgYGIayfhYY5+KFCxgK9A0MCMoNdf1MGDIjDIwGwEA7YKDBaAAMtAMGGjCOVoNQsH7tWgwFgcHBBOWGuv4RnwVGA2CgHTDQYDQABtoBAw1GfDXI+PnHj/9k6R4mAACah2OpZk6p1wAAAABJRU5ErkJggg=="
	},
	{
		name: "类型10",
		data: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAQCAYAAACm53kpAAAAAXNSR0IArs4c6QAAAHdJREFUWIXtlzEOwCAMAw0P4P/PCg8Ij4AlG52YOiDRSi4lNxlFliwHBkIz67VWrJBSAgDs7I/jkEWQRW56NtvdH3E4XgA7ABsvgB2AjRcwRFFFUb3p2ewrrOZ/7QY8LZC1AH8C7ABsvAB2ADbh9N9gaGZ9yf0TLkb7xOQRGQfVAAAAAElFTkSuQmCC"
	},
];