// type取自png文件名开头数字，无数字默认为1 
 
 
const ROAD_IMAGES = [ 
	{
		name: "道路1",
		
		data: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAAXNSR0IArs4c6QAAAHpJREFUaIHt1LENgCAQQFGxNbFwB/dyD2v3cC93sDCx1o6ORO4MHPBfT+ATDrcdy9MprPPuNOu1+pyb/yEYMFxnynOIBQPucUp5DrF6n1ApCMitzQBLX6wowNIX6wMs3WoMH2DpVmO0OcSWfAoodT4AAAAAAAAAAECdXi2DDwvtQWQpAAAAAElFTkSuQmCC"
	},
	{
		name: "道路2",
		
		data: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAAXNSR0IArs4c6QAAAKBJREFUaIHt1bENgzAUhOHDXRrWyCqskAlZgVVYww0lVLYiodjGSqRT+L/e0h28Zw+v5bnrorhFjY9RkjRP63D1/DeFnkMpvIOmAnGLv87RrVoghXctkQt8CpjGxWls3uUCpYCu4aXOJXbSVcBpH/7vD7R8XaedOBVwCteieo26C1L9sXIu17TEzmMVJP/XtqT4EjuPDgAAAAAAAAAAuK8DCAUoIGzXQw0AAAAASUVORK5CYII="
	},
	
		
]; 
